document.documentElement.classList.add('js');
const inventory=(window.usedInventoryData?.vehicles||[]).filter(v=>v.locationId==='18393').map(v=>({...v,id:v.vin,name:v.title.replace(/^(?:Used|New) [0-9]{4} /i,''),newUsed:v.condition||'Used',type:'Unverified',drivetrain:'Unverified',engine:'Verify on sticker',features:[],scoreBoost:[]}));
const SNAPSHOT_DATE=window.usedInventoryData?.capturedAt||'Unknown';
const money=n=>n===null?'Call for Price':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n);
const safe=s=>(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=s=>(s||'').toLowerCase().replace(/cooled seats/g,'ventilated seats').replace(/surround[- ]view/g,'360 camera').replace(/four[- ]wheel drive/g,'4wd').replace(/(?:three|3)[- ]rows?/g,'3 rows');
const carEmoji=t=>t==='Truck'?'🛻':t==='Car'?'🚘':t==='Minivan'?'🚐':'🚙';
function parseMoney(q){const re=/(?:under|less than|max(?:imum)?|budget(?: of)?|up to|around|below)\s*\$?([0-9]+(?:,[0-9]{3})*(?:\.[0-9]+)?)\s*(k)?\b/gi;for(const m of q.matchAll(re)){if(/^\s*(?:miles|mi)\b/i.test(q.slice(m.index+m[0].length)))continue;return Math.round(Number(m[1].replace(/,/g,''))*(m[2]?1000:1))}return null}
function parseMiles(q){const m=q.match(/(?:under|max(?:imum)?|less than|below)\s*([0-9]+(?:,[0-9]{3})*(?:\.[0-9]+)?)\s*(k)?\s*(?:miles|mi)\b/i);return m?Math.round(Number(m[1].replace(/,/g,''))*(m[2]?1000:1)):null}


const invGrid=document.getElementById('inventoryGrid');let currentFilter='all';
function renderInventory(){if(!invGrid)return;const filtered=inventory.filter(v=>currentFilter==='all'||v.newUsed===currentFilter||v.type===currentFilter);invGrid.innerHTML=filtered.map(v=>`<article class="inventory-card"><div class="vehicle-art"><span class="vehicle-status">${v.newUsed}</span><span class="car-icon">${carEmoji(v.type)}</span><span class="verified-stock">Stock ${safe(v.stock)}</span></div><div class="inventory-card-copy"><span class="chip">PUBLIC LISTING SNAPSHOT</span><h3>${v.year} ${safe(v.name)}</h3><div class="inventory-price">${money(v.price)}</div><div class="inventory-meta"><span>${safe(v.type)}</span><span>${safe(v.drivetrain)}</span>${v.newUsed==='Used'?`<span>${v.miles.toLocaleString()} miles</span>`:''}<span>${safe(v.engine)}</span>${v.features.slice(0,4).map(x=>`<span>${safe(x)}</span>`).join('')}</div><div class="vin-line">VIN ${safe(v.vin)}</div><div class="inventory-actions"><a class="mini-btn" href="compare.html">Compare</a><a class="mini-btn alt" href="${v.sourceUrl}" target="_blank" rel="noopener">Official listing ↗</a><a class="mini-btn" href="contact.html">Ask us</a></div></div></article>`).join('')}
if(invGrid){renderInventory();document.querySelectorAll('[data-inventory-filter]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-inventory-filter]').forEach(x=>x.classList.remove('active'));b.classList.add('active');currentFilter=b.dataset.inventoryFilter;renderInventory()}))}

const aSel=document.getElementById('vehicleA'),bSel=document.getElementById('vehicleB'),compOut=document.getElementById('compareOutput');
function fillSelect(sel){if(!sel)return;inventory.forEach(v=>{const o=document.createElement('option');o.value=v.id;o.textContent=`${v.year} ${v.name} — ${money(v.price)}`;sel.appendChild(o)})}
function renderCompare(){if(!aSel||!bSel||!compOut)return;const a=inventory.find(v=>v.id===aSel.value),b=inventory.find(v=>v.id===bSel.value);if(!a||!b)return;const shared=a.features.filter(x=>b.features.includes(x)),aOnly=a.features.filter(x=>!b.features.includes(x)),bOnly=b.features.filter(x=>!a.features.includes(x));compOut.innerHTML=`<div class="comparison-summary"><div class="compare-vehicle"><span>VEHICLE A • ${safe(a.stock)}</span><h3>${a.year} ${safe(a.name)}</h3><p>${money(a.price)} • ${a.newUsed} • ${safe(a.drivetrain)}</p><small>VIN ${safe(a.vin)}</small></div><div class="compare-vehicle"><span>VEHICLE B • ${safe(b.stock)}</span><h3>${b.year} ${safe(b.name)}</h3><p>${money(b.price)} • ${b.newUsed} • ${safe(b.drivetrain)}</p><small>VIN ${safe(b.vin)}</small></div></div><div class="comparison-table"><div><span>Shared</span><b>${shared.join(' • ')||'No shared tracked features'}</b></div><div><span>A only</span><b>${aOnly.join(' • ')||'—'}</b></div><div><span>B only</span><b>${bOnly.join(' • ')||'—'}</b></div><div><span>Price gap</span><b>${money(Math.abs(a.price-b.price))}</b></div></div><div class="compare-source-row"><a class="mini-btn alt" href="${a.sourceUrl}" target="_blank" rel="noopener">Vehicle A official listing ↗</a><a class="mini-btn alt" href="${b.sourceUrl}" target="_blank" rel="noopener">Vehicle B official listing ↗</a><span>Saved snapshot checked ${SNAPSHOT_DATE}</span></div>`}
if(aSel&&bSel){fillSelect(aSel);fillSelect(bSel);aSel.value='r12377';bSel.value='r12558';aSel.addEventListener('change',renderCompare);bSel.addEventListener('change',renderCompare);renderCompare()}

document.querySelectorAll('[data-review-filter]').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('[data-review-filter]').forEach(x=>x.classList.remove('active'));btn.classList.add('active');const f=btn.dataset.reviewFilter;document.querySelectorAll('[data-person]').forEach(q=>q.classList.toggle('hidden',f!=='all'&&q.dataset.person!==f))}));

const advisorParam=new URLSearchParams(location.search).get('advisor');const advisorSelect=document.getElementById('contactAdvisor');if(advisorParam&&advisorSelect&&[...advisorSelect.options].some(o=>o.value===advisorParam))advisorSelect.value=advisorParam;

const menuToggle=document.querySelector('.menu-toggle'), primaryNav=document.getElementById('primary-nav');
menuToggle?.addEventListener('click',()=>{const open=menuToggle.getAttribute('aria-expanded')!=='true';menuToggle.setAttribute('aria-expanded',String(open));primaryNav?.classList.toggle('is-open',open)});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&menuToggle?.getAttribute('aria-expanded')==='true'){menuToggle.setAttribute('aria-expanded','false');primaryNav?.classList.remove('is-open');menuToggle.focus()}});

