import {parseQuery,matchVehicle,definitions} from './equipment-search.mjs?v=23-tow26';
const $=id=>document.getElementById(id),inventory=window.usedInventoryData,index=window.equipmentIndex;
const el=(tag,text)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;return n;};
function compareGroup(){
 const out=$('group-results');out.replaceChildren();const text=$('group-query').value.trim();if(!text){out.append(el('p','Enter a model and any must-have features.'));return;}
 const q=parseQuery(text);if(q.ambiguity||q.warnings.some(w=>/Conflicting|not both|More than one/.test(w))){out.append(el('p',q.ambiguity||q.warnings.join(' ')));return;}
 const selected=$('group-condition').value;if(q.condition&&selected!=='Both'&&q.condition!==selected){out.append(el('p',`Choose ${q.condition} above to match your request.`));return;}q.condition=selected==='Both'?null:selected;
 const base={...q,requirements:[]};const rows=inventory.vehicles.filter(v=>matchVehicle(v,index.records[v.vin],base).kind==='match').map(v=>({v,s:index.records[v.vin],result:matchVehicle(v,index.records[v.vin],q)}));
 rows.sort((a,b)=>(a.result.kind==='match'?0:1)-(b.result.kind==='match'?0:1)||(a.v.price??Infinity)-(b.v.price??Infinity));
 const confirmed=rows.filter(r=>r.result.kind==='match').length;
 out.append(el('h3',q.requirements.length?`${confirmed} of ${rows.length} vehicles confirm every requested feature`:`${rows.length} vehicles to compare`),el('p','Saved inventory at 8107 Research Blvd. Confirm current availability. “Not confirmed” is not a claim that equipment is absent. Scroll sideways to compare every vehicle.'));
 if(!rows.length){out.append(el('p','No vehicles match that model, condition and budget in the saved inventory.'));return;}
 if(q.requirements.length&&!confirmed)out.append(el('p','No exact match is confirmed. The table below shows which requested features are listed for each vehicle.'));
 if(q.requirements.length&&confirmed){const shortlist=el('div');shortlist.className='search-summary';shortlist.append(el('h3','Start with these vehicles'));for(const {v} of rows.filter(r=>r.result.kind==='match')){const a=el('a',`${v.stock||v.vin} — ${v.title}`);a.href='contact.html?vehicle='+v.vin+'&request='+encodeURIComponent(text);shortlist.append(a,el('br'));}out.append(shortlist);}
 const details=el('details');details.append(el('summary','Compare equipment across these vehicles'));out.append(details);
 const label=el('label'),toggle=el('input');toggle.type='checkbox';toggle.checked=true;label.append(toggle,document.createTextNode(q.requirements.length?' Show only my requested features':' Show differences only'));details.append(label);
 const wrap=el('div');wrap.className='equipment-table-wrap';const table=el('table');table.className='equipment-table';const head=el('thead'),hr=el('tr');hr.append(el('th','Equipment'));
 for(const {v,s,result} of rows){const th=el('th');th.scope='col';th.style.minWidth='230px';th.append(el('strong',v.stock||v.vin),el('p',v.title),el('p',v.price==null?'Call for price':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(v.price)));if(q.requirements.length)th.append(el('p',result.kind==='match'?'✓ All requested features confirmed':result.kind==='excluded'?'Requested feature conflict':'Needs equipment confirmation'));if(s?.status==='verified'){const a=el('a','Original sticker ↗');a.href=s.sourceUrl;th.append(a);}hr.append(th);}head.append(hr);table.append(head);
 const body=el('tbody'),requested=new Set(q.requirements.map(r=>r.id));const defs=[...definitions].sort((a,b)=>Number(requested.has(b[0]))-Number(requested.has(a[0])));
 for(const [id,name] of defs){const facts=rows.map(r=>r.s?.status==='verified'?r.s.features[id]:null);const differing=new Set(facts.map(f=>f?.value===true?'yes':f?.value===false?'no':'unknown')).size>1;const tr=el('tr');tr.dataset.keep=String(requested.size?requested.has(id):differing);tr.hidden=tr.dataset.keep==='false';const th=el('th',(requested.has(id)?'★ ':'')+name);th.scope='row';tr.append(th);for(const f of facts){const td=el('td');td.append(el('strong',f?.value===true?'✓ Listed':f?.value===false?'Explicitly excluded':'Not confirmed'));if(f)td.append(el('p',f.evidence.join(' / ')));if(f?.sourceUrl){const a=el('a','Factory instructions ↗');a.href=f.sourceUrl;td.append(a);}tr.append(td);}body.append(tr);}
 table.append(body);wrap.append(table);details.append(wrap);toggle.addEventListener('change',()=>{for(const row of body.children)row.hidden=toggle.checked&&row.dataset.keep==='false';});out.scrollIntoView({behavior:'instant',block:'start'});
}
$('group-compare').addEventListener('click',compareGroup);$('group-query').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();compareGroup();}});
