import {equipmentRows,equipmentExplanation,selectedTrimIds,featureMatches} from './trim-comparison.mjs?v=20261004-audit1';
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const designs=[
 {id:1,title:'The complete table',short:'Everything side by side',description:'One familiar table. Features run down the left; every trim runs across the top. Scroll sideways to see more trims.',recommendation:'Best for shoppers who want all researched details in one place. Can feel wide on a phone.'},
 {id:2,title:'Easy sections',short:'My recommendation',description:'The same equipment table, organized into simple sections. Open only the subjects you care about, such as comfort or off-road equipment.',recommendation:'My recommendation: a clear starting view, fewer rows at once, and the full detail one tap away.'},
 {id:3,title:'The bubble board',short:'Fastest color scan',description:'A compact chart puts the colored bubbles first. The actual specification stays underneath, so matching green circles do not hide different equipment.',recommendation:'Closest to your original idea. Great for a quick overview; longer package descriptions still need room.'},
 {id:4,title:'One feature at a time',short:'Easiest on a phone',description:'Each feature gets its own card, with every trim listed underneath. Read straight down without moving a wide table sideways.',recommendation:'Best phone layout. I would pair this with option 2 on larger screens.'},
 {id:5,title:'Pick two, see the difference',short:'Best for a final decision',description:'Choose any two trims from the full model lineup. Keep the same equipment detail, with more room for the trims you are actually considering.',recommendation:'A useful final step after the full lineup helps a shopper narrow the choice.'}
];
const status={standard:['✓','Standard'],optional:['+','Optional / package'],unavailable:['−','Not offered'],verify:['?','Verify']};
let data,model,design=2,selected=[];
const accepted=document.body.dataset.layout==='accepted',phoneLayout=matchMedia('(max-width:760px)');
const params=new URLSearchParams(location.search);design=!accepted&&designs.some(d=>d.id===+params.get('design'))?+params.get('design'):2;
function category(row){const k=(row.key+' '+row.label).toLowerCase();if(/camera|park|blind|brak.*assist|collision|cruise|safety|lane|pedestrian|airbag|sensing/.test(k))return 'Parking & driver assistance';if(/screen|display|audio|speaker|navigation|connect|entertainment|charging|radio|wifi|wi-fi/.test(k))return 'Screens & sound';if(/seat|upholstery|leather|climate|heated.wheel|steering.wheel.*heat|cabin|sunroof|panoramic|vacuum|console/.test(k))return 'Comfort & seating';if(/engine|powertrain|transmission|gearbox|drive.system|awd|electric.range|battery|motor/.test(k))return 'Engine & drive';if(/differential|sway|axle|transfer|suspension|skid|rock.rail|off.road|tire|wheel/.test(k))return 'Wheels & capability';return 'Body & everyday use'}
const groupDescriptions={'Comfort & seating':'Materials, comfort and how you use the cabin.','Screens & sound':'Screen sizes, navigation and audio systems.','Parking & driver assistance':'Visibility and assistance equipment. The driver remains responsible.','Engine & drive':'Compare the stated engine, transmission and drive system.','Wheels & capability':'Wheel and tire specifications, suspension and trail hardware.','Body & everyday use':'Doors, cargo, lighting and useful exterior equipment.'};
function rowsFor(trims){return equipmentRows(trims).map(row=>({...row,category:category(row)}));}
function comparedTrims(){return accepted||design===5?model.trims.filter(t=>selected.includes(t.id)):model.trims;}
function detailsText(f){return [...new Set([f?.note,f?.benefit].filter(Boolean))].map(x=>`<p class="equipment-note">${esc(x)}</p>`).join('');}
function cell(f){const key=f?.status||'verify',s=status[key];return `<div class="status-line"><i class="bubble ${key}" aria-hidden="true">${s[0]}</i><span class="status-word">${s[1]}</span></div><span class="cell-value">${esc(f?.value||'Not confirmed in this guide')}</span>${f?.note?`<small class="cell-qualification">${esc(f.note)}</small>`:''}` }
function photo(t){return (t.imageUrl?`<img src="${esc(t.imageUrl)}" alt="${esc(model.year+' '+model.name+' '+t.name)}" loading="lazy">`:'<span class="trim-photo-pending">Trim photo unavailable</span>')+(t.availabilityNote?`<small class="availability-note">${esc(t.availabilityNote)}</small>`:'')}
function label(r){return `<button class="feature-info" data-feature="${esc(r.key)}" aria-label="${esc(r.label+' — explanation and sources')}">${esc(r.label)}<span>Details &amp; source ↗</span></button>`}
function table(rows,trims,compact=false){return `<div class="matrix-scroll${compact?' compact-matrix':''}" role="region" tabindex="0" aria-label="Scrollable factory equipment table"><table class="matrix" style="--trim-count:${trims.length}"><caption>${esc(model.year+' '+model.name+' factory equipment')}</caption><thead><tr><th scope="col" class="feature-column">Factory equipment</th>${trims.map(t=>`<th scope="col" class="trim-heading">${photo(t)}<strong>${esc(t.name)}</strong></th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr data-feature-row="${esc(r.key)}"><th scope="row" class="feature-column">${label(r)}</th>${r.cells.map(f=>`<td data-status="${f?.status||'verify'}">${cell(f)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`}
function trimPictures(trims){return `<div class="model-filmstrip" aria-label="Trim illustrations">${trims.map(t=>`<figure>${photo(t)}<figcaption>${esc(t.name)}</figcaption></figure>`).join('')}</div>`}
function featureCards(rows,trims,includePictures=true){return (includePictures?trimPictures(trims):'')+`<div class="feature-cards">${rows.map(r=>`<article class="feature-card" data-feature-row="${esc(r.key)}"><header><h3>${label(r)}</h3><p>${esc(equipmentExplanation(r))}</p></header>${trims.map((t,i)=>`<div class="feature-trim"><strong>${esc(t.name)}</strong><div data-status="${r.cells[i]?.status||'verify'}">${cell(r.cells[i])}</div></div>`).join('')}</article>`).join('')}</div>`}
function render(){
 if(!accepted){
 const d=designs.find(d=>d.id===design);$('#design-label').textContent='Option '+design+' of 5';$('#design-title').textContent=d.title;$('#design-explanation').textContent=d.description;$('#design-recommendation').textContent=d.recommendation;$('#current-example').textContent=design+'. '+d.title;
 $('#designs').innerHTML=designs.map(x=>`<button class="design-choice" data-design="${x.id}" aria-current="${x.id===design}"><span class="mini mini-${x.id}" aria-hidden="true">${'<i></i>'.repeat(12)}</span><b>${x.id}. ${esc(x.title)}</b><small>${esc(x.short)}</small></button>`).join('');
 }
 $('#table-year').textContent=model.year+' · Factory trim guide';$('#table-model-title').textContent=model.name;$('#table-scope').textContent=model.comparisonScope||model.scope;$('#table-coverage').textContent=model.coverageNote||model.scope;
 if(!$('#comparison-notes'))$('#table-coverage').insertAdjacentHTML('afterend','<div id="comparison-notes"></div>');
 const notes=[model.comparisonNote,...(Array.isArray(model.comparisonNotes)?model.comparisonNotes:model.comparisonNotes?[model.comparisonNotes]:[])].filter(Boolean);
 $('#comparison-notes').innerHTML=[...new Set(notes)].map(note=>`<p>${esc(note)}</p>`).join('');
 if(!$('#year-coverage'))$('#table-scope').insertAdjacentHTML('afterend','<p id="year-coverage" class="year-coverage"></p>');
 $('#year-coverage').hidden=model.year!==2027;$('#year-coverage').textContent=model.year===2027?'2027 announcement guide — '+(model.coverageNote||'Published details only; complete factory equipment specifications are pending.'):'';
 const sources=new Map((model.sources||[]).map(s=>[s.url,s.label]));for(const t of model.trims)for(const f of t.comparison||[])if(!sources.has(f.sourceUrl))sources.set(f.sourceUrl,new URL(f.sourceUrl).hostname+' — equipment source');
 $('#table-sources').innerHTML=[...sources].map(([url,name])=>`<li><a href="${esc(url)}" target="_blank" rel="noopener noreferrer">${esc(name)}</a></li>`).join('');if(!accepted)$('#back-to-cards').href='trim-design-preview.html?design=1&model='+encodeURIComponent(model.id);
 renderEquipment();updateUrl();
}
function renderEquipment(){
 const output=$('#table-output'),openGroups=new Set([...output.querySelectorAll('details[open][data-group]')].map(g=>g.dataset.group)),hadGroups=!!output.querySelector('[data-group]');
 const focus=accepted||design===5;$('#focus-trims').hidden=!focus;
 $('#focus-trims').innerHTML=focus?`<p class="focus-label">${accepted?'Choose the trims you want to compare. Tap a selected trim to remove it.':'Choose two trims. Remove one to pick another.'}</p>${accepted?'<div class="trim-selection-actions"><button type="button" data-selection="all">All trims</button><button type="button" data-selection="clear">Clear selections</button></div>':''}<div class="focus-choices" role="group" aria-label="Choose trims to compare">${model.trims.map(t=>`<button type="button" data-trim="${esc(t.id)}" aria-pressed="${selected.includes(t.id)}">${selected.includes(t.id)?'✓ ':''}${esc(t.name)}</button>`).join('')}</div>`:'';
 const trims=comparedTrims();
 if(!$('#trim-configuration'))$('#focus-trims').insertAdjacentHTML('afterend','<details id="trim-configuration" class="trim-configuration"><summary>Configuration used for this comparison</summary><div></div></details>');
 const configurationNotes=new Map();for(const t of trims){if(t.comparisonNote){const names=configurationNotes.get(t.comparisonNote)||[];names.push(t.name);configurationNotes.set(t.comparisonNote,names)}}
 $('#trim-configuration').hidden=!configurationNotes.size;$('#trim-configuration div').innerHTML=[...configurationNotes].map(([note,names])=>`<p><strong>${esc(names.join(' · '))}</strong>${esc(note)}</p>`).join('');
 if(!trims.length){$('#table-output').innerHTML='<p class="empty-state">Choose your first trim above.</p>';$('#table-count').textContent='';return}
 const all=rowsFor(trims),q=$('#feature-search').value.trim().toLowerCase(),diff=$('#differences-only').checked;
 const rows=all.filter(r=>(!diff||r.knownDifference)&&featureMatches(r,q));
 $('#table-count').textContent=`${rows.length} of ${all.length} researched features · ${trims.length} ${trims.length===1?'trim':'trims'}${diff?' · Confirmed differences':''}`;
 if(!rows.length){$('#table-output').innerHTML=all.length?`<p class="empty-state">${diff&&trims.length<2?'Choose at least two trims to see differences.':diff&&!q?'No confirmed differences in the recorded features. Missing details are still unverified; this does not establish that these trims have identical equipment. Turn off “Show differences only” to see all recorded features.':'No matching researched features. Try a broader word or turn off “Show differences only.”'}</p>`:trimPictures(trims)+'<p class="empty-state">These trims have been announced. Their factory equipment details are not yet verified in this guide.</p>';return}
 const hint=trims.length>2?'<p class="scroll-note">Swipe or scroll sideways for more trims. Feature names stay on the left.</p>':'';
 if(design===2){const groups=[...new Set(rows.map(r=>r.category))];const preferred=['Comfort & seating','Screens & sound','Parking & driver assistance','Wheels & capability','Engine & drive','Body & everyday use'];groups.sort((a,b)=>preferred.indexOf(a)-preferred.indexOf(b));const mobile=accepted&&phoneLayout.matches;output.dataset.layout=mobile?'feature-cards':'grouped-table';output.innerHTML=(mobile?trimPictures(trims):hint)+groups.map((g,i)=>{const list=rows.filter(r=>r.category===g),isOpen=q?true:!accepted||!hadGroups?i===0:openGroups.has(g);return `<details class="equipment-group" data-group="${esc(g)}" ${isOpen?'open':''}><summary><span>${esc(g)}<small>${list.length} ${list.length===1?'feature':'features'}</small></span></summary><p class="group-intro">${esc(groupDescriptions[g])}</p>${mobile?featureCards(list,trims,false):table(list,trims)}</details>`}).join('')}
 else if(design===4)$('#table-output').innerHTML=featureCards(rows,trims);
 else $('#table-output').innerHTML=hint+`<div class="${focus?'focus-matrix':''}">${table(rows,trims,design===3)}</div>`;
 if(params.get('qa')==='1')document.documentElement.dataset.ready='true';
}
function updateUrl(){const p=new URLSearchParams(accepted?{model:model.id}:{design,model:model.id});if(selected.length<model.trims.length)p.set('trims',selected.join(','));history.replaceState(null,'',location.pathname+'?'+p+(params.has('qa')?'&qa=1':'')+location.hash);}
function chooseModel(id,initial=false){model=data.models.find(m=>m.id===id)||data.models[0];$('#table-brand').value=model.brand;const models=data.models.filter(m=>m.brand===model.brand);const years=[...new Set(models.map(m=>m.year))].sort((a,b)=>b-a);$('#table-model').innerHTML=years.map(year=>`<optgroup label="${year} models">${models.filter(m=>m.year===year).map(m=>`<option value="${esc(m.id)}">${esc(m.name+' · '+m.year)}</option>`).join('')}</optgroup>`).join('');$('#table-model').value=model.id;selected=accepted?selectedTrimIds(model,initial?params.get('trims'):null):model.trims.slice(0,2).map(t=>t.id);$('#feature-search').value='';$('#differences-only').checked=false;$('#table-output').innerHTML='';render();}
$('#designs')?.addEventListener('click',e=>{const b=e.target.closest('[data-design]');if(b){design=+b.dataset.design;render();$('#equipment').scrollIntoView({behavior:'instant',block:'start'})}});
$('#table-brand').addEventListener('change',()=>chooseModel(data.models.find(m=>m.brand===$('#table-brand').value).id));$('#table-model').addEventListener('change',()=>chooseModel($('#table-model').value));
$('#feature-search').addEventListener('input',renderEquipment);$('#differences-only').addEventListener('change',renderEquipment);
$('#focus-trims').addEventListener('click',e=>{const action=e.target.closest('[data-selection]');if(action){selected=action.dataset.selection==='all'?model.trims.map(t=>t.id):[];renderEquipment();updateUrl();$('#focus-trims').querySelector(`[data-selection="${action.dataset.selection}"]`)?.focus({preventScroll:true});return}const b=e.target.closest('[data-trim]');if(!b)return;const id=b.dataset.trim;if(selected.includes(id))selected=selected.filter(x=>x!==id);else if(accepted||selected.length<2)selected.push(id);else{const p=$('.focus-label');p.textContent='Two trims are selected. Tap a selected trim to remove it, then choose another.';p.setAttribute('role','status');return}renderEquipment();updateUrl();[...$('#focus-trims').querySelectorAll('[data-trim]')].find(x=>x.dataset.trim===id)?.focus({preventScroll:true})});
$('#table-output').addEventListener('click',e=>{const b=e.target.closest('[data-feature]');if(!b)return;const trims=comparedTrims(),row=rowsFor(trims).find(r=>r.key===b.dataset.feature);$('#feature-title').textContent=row.label;$('#feature-details').innerHTML=`<p>${esc(equipmentExplanation(row))}</p>`+trims.map((t,i)=>`<section><h3>${esc(t.name)}</h3>${cell(row.cells[i])}${detailsText(row.cells[i])}${row.cells[i]?.sourceUrl?`<a class="source-link" href="${esc(row.cells[i].sourceUrl)}" target="_blank" rel="noopener noreferrer">View equipment source ↗</a>`:'<p>No sourced answer recorded for this trim yet.</p>'}${t.comparisonNote?`<p class="configuration-note">${esc(t.comparisonNote)}</p>`:''}</section>`).join('');$('#feature-dialog').showModal()});
$('#feature-dialog .close').addEventListener('click',()=>$('#feature-dialog').close());$('.dialog-done').addEventListener('click',()=>$('#feature-dialog').close());
phoneLayout.addEventListener('change',()=>{if(accepted&&model)renderEquipment()});
try{const response=await fetch('trim-standard-data.json');if(!response.ok)throw Error('Catalog unavailable');data=await response.json();chooseModel(params.get('model')||(accepted?'wrangler':'chrysler-pacifica'),true);document.documentElement.dataset.ready='true'}catch(e){$('#table-output').innerHTML='<p class="empty-state">The equipment guide could not load. Please refresh the page.</p>';console.error(e)}

